const INIT_WEBBSOCKET = 'WS_INIT'
const SET_SID = 'SET_SID'
const SET_USER = 'SET_USER'
const SER_ISLOGIN = 'SET_ISLOGGIN'
const SET_MSG = 'SET_MSG'
const SET_TOKEN = 'SET_TOKEN'
const SET_HIDDE = 'SET_HIDDE'

export {
  INIT_WEBBSOCKET,
  SET_SID,
  SET_USER,
  SER_ISLOGIN,
  SET_TOKEN,
  SET_MSG,
  SET_HIDDE
}
