const INIT_WEBBSOCKET = 'WS_INIT'
const SET_SID = 'SET_SID'
const SET_USER = 'SET_USER'
const SET_ISLOGIN = 'SET_ISLOGGIN'
const SET_MSG = 'SET_MSG'
const SET_TOKEN = 'SET_TOKEN'
const SET_HIDDE = 'SET_HIDDE'
const SET_USERID = 'SET_USERID'
const USER_KEY = 'USER-KEY'

export {
  INIT_WEBBSOCKET,
  SET_SID,
  SET_USER,
  SET_ISLOGIN,
  SET_TOKEN,
  SET_MSG,
  SET_HIDDE,
  SET_USERID,
  USER_KEY
}
